language: java

jdk:
  - oraclejdk8

script:
  mvn clean package -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  
before_deploy:
- export TRAVIS_TAG="v1.1.1"
- echo "$TRAVIS_TAG" "$TRAVIS_COMMIT"
- git config --local user.name "$USER_NAME"
- git config --local user.email "$USER_EMAIL"
- git tag $TRAVIS_TAG

deploy:
  provider: releases
  tag_name: $TRAVIS_TAG
    target_commitish: $TRAVIS_COMMIT
  name: $TRAVIS_TAG
  api_key: "${GITHUB_OAUTH_TOKEN}"
  file: "target/open-commons-spring4.jar"
  skip_cleanup: true
#  draft: true
  on:
    tags: true
  overwrite: true
  
  notifications:
    email:
      on_success: never
      on_failure: always
