language: java

jdk:
  - oraclejdk8

script:
  mvn clean package -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  
before_deploy:
# Set up git user name and tag this commit
- git config --local user.name "$USER_NAME"
- git config --local user.email "$USER_EMAIL"
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
- git tag $TRAVIS_TAG"-BUILD"

deploy:
  provider: releases
  tag_name: $TRAVIS_TAG"-BUILD"
  api_key: "${GITHUB_OAUTH_TOKEN}"
  file: "target/open-commons-spring4.jar"
  skip_cleanup: true
#  draft: true
  on:
    tags: true
  overwrite: true
  
  notifications:
    email:
      on_success: never
      on_failure: always
